config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/gdpr'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/orders.rb
class Order < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :image_url, :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController

  def index
  end

  def landing_page
    @featured_book = Book.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="page-contents">
  <h1>Editing Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Show', @book %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-contents">

  <h1>Books</h1>

  <div class="container-fluid">
    <div class="row">
      <% @books.each do |book| %>
      <div class="product col-xs-6 col-md-4 col-lg-2">
        <div class="title_header">
          <h5><%=link_to book.name, book %></h5>
        </div>
        <div class="title_thumbnail">
          <%= image_tag(book.image_url, class: "img-responsive") if book.image_url %>
        </div>
        <div class="title_content">
          <dl>
            <strong>Author: </strong><%= book.author %>
          </dl>
          </div>
        <dl>
          <strong>price: </strong>€<%= book.price %>
        </dl>

        <%= link_to 'Show', book %>
        <%= link_to 'Edit', edit_book_path(book) %>
        <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>
    </div>
  </div>
<%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.html.erb
<div class="page-contents">
  <h2>New Book</h2>

  <%= render 'form', book: @book %>

  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-contents">
  <p>
    <strong>Title:</strong>
    <%= @book.name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @book.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= @book.image_url %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @book.price %>
  </p>

  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrunoApp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--  need to understand what the csp meta tag means. Other students deleted the line -->
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand"><%= link_to "Aleph Books", root_path %></div>
          <!-- removed home from navbar and successfully added rb link to navbar-brand :)  -->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Store", books_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <%= yield %>
    <footer class="footer">
      <div class="container">
        <footer>
          <p>&copy; 2018 Bruno Correia. This page complies with GDPR. Click <%= link_to "here", simple_pages_gdpr_path %>
     for more info.</p>
        </footer>
      </div>
    </footer>
  </body>
</html>

app/views/simple_pages/about.html.erb
<div class="page-contents">
  <h1>About</h1>
  <p>Throughout the years, I had several music instruments. Each one has a story behind it. Some are gone, others joined the collection.</p>
  <p>Now it's time they find new music lovers. </p>
</div>

app/views/simple_pages/contact.html.erb
<div class="page-contents">
  <h1>Contact</h1>
  <p>Fell in love with any of the instruments?</p>
  <p><a href="mailto:sicknsour@gmail.com">Click here to get in touch and check the prices.<a></p>
  <p>PS: no data from clients will be stored.</p>
</div>

app/views/simple_pages/gdpr.html.erb
<div class="page-contents">
  <h1>GDPR</h1>
  <p>This page doesn't store any data from users. Yet.</p>
</div>

app/views/simple_pages/index.html.erb
<div class="page-contents">
  <h1>Welcome to Bruno's Book Store</h1>
  <h2>Great books for great prices</h2>
  <p>The best books I have worked with.</p>

  <div class="container-fluid">
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
    <div class="product col-xs-6 col-md-4 col-lg-2">
      <%= image_tag("book_filho.jpg", class: "img-responsive product_img", alt: "xxx") %>
    </div>
  </div>
</div>

app/views/simple_pages/landing_page.html.erb
<div class="page-contents">
  <h2>Featured Book</h2>
  <%= @featured_book.name %>
</div>